### ISSUE TITLE
Image assumes mmc location

### ISSUE THREAD

**Issue by nicman23** [Debian/raspi3-image-spec#17]
you should probably use labels for fstab and cmdline (and of course name the partitions accordingly)

**Comment by stapelberg** [comment]
Not sure I follow. The image has a defined partition table, what’s wrong with making assumptions about those partitions?

**Comment by nicman23** [comment]
the assumption is that an sd card will be used. using a usb device such as a usb stick with its block device in `/dev/sda` fails to boot. also, I know RPi has only one mmc device, but it is bad form to use them in fstab and kernel's cmdline.

**Comment by stapelberg** [comment]
Okay. Can you send a pull request for this as well please?

**Comment by nicman23** [comment]
i am not familiar with yaml that builds the image, where can i get some documentation?

**Comment by stapelberg** [comment]
We’re using vmdb2. Maybe https://github.com/larswirzenius/vmdb2/blob/master/doc/en/000.mdwn is a good start? Otherwise, feel free to browse https://github.com/larswirzenius/vmdb2.

**Comment by gwolf** [comment]
This has been fixed in our HEAD. No images have yet been produced with this, I'm holding off producing an image until I get time to update and test an updated raspi3-firmware that enables wifi on the 3B+.
