### ISSUE TITLE
Built my own image; FS is not resized to fill card

### ISSUE THREAD

**Issue by oxwivi** [Debian/raspi3-image-spec#20]
I'm not sure if the images built is supposed to autoreize, but it did not in my case at least.
```
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
mmcblk0     179:0    0 14.9G  0 disk 
|-mmcblk0p1 179:1    0  299M  0 part /boot/firmware
`-mmcblk0p2 179:2    0  1.2G  0 part /
```
What do I do to resize it now, and how do I make future images to auto resize?

**Comment by chrisnew** [comment]
To resize it for now manually: You can delete and re-create the partition using fdisk. After that, you can enlarge the ext4 filesystem using resize2fs.

**Comment by oxwivi** [comment]
Yeah, Googled and found [instructions](
https://elinux.org/RPi_Resize_Flash_Partitions#Manually_resizing_the_SD_card_on_Raspberry_Pi) to do that.

So the image isn't supposed to automatically do the resizing?

**Comment by jlu5** [comment]
Another option is to resize the SD card from a card reader after copying the image out - GParted did it nice and easy for me.

**Comment by gwolf** [comment]
I have just replaced rpi3-resizerootfs with a new version; to the extent I have tested, this issue should be solved. Feel free to reopen if you still have issues.
