### ISSUE TITLE
Cannot resolve user name systemd-timesync: No such process

### ISSUE THREAD

**Issue by Merovius** [Debian/raspi3-image-spec#38]
On a fresh install, systemd-timesyncd failed to start with

    Dec 14 22:42:10 rpi3 systemd-timesyncd[24567]: Cannot resolve user name systemd-timesync: No such process

Creating that user fixed the issue. It would be good if that user would exist from the get-go :)

**Comment by gwolf** [comment]
Have not been able to reproduce this issue. Am closing it, please reopen if you can provide more information!
