### ISSUE TITLE
on which platform to carry out

### ISSUE THREAD

**Issue by zd59** [Debian/raspi3-image-spec#39]
HI!

Sorry, but from the text here I can not guess, on which platform this manual must be executed?
Image created is for ARM64, in text are "apt install". Confused: if I'm creating an image from packages installed, this means, that the system is already installed and I'm logged in. If this is not correct, the installed packages (apt install) are not for arm64 and will not work there.
So what existed first, egg or chicken?
Please uncover the above secret.
My posibilities are ARM32 raspbian or Slackware64 on Intel. If needed, I can install Virtualbox Debian machine on Intel platform.

Hardly waiting for the answer.

Best regards,

Zdenko

**Comment by chschlue** [comment]
vmdb2 will download and install arm64 packages, your host platform doesn't matter.

**Comment by zd59** [comment]
Thank you Christian.

I figured out that myself, when installed Debian on VirtualBox.

Regards,

Zdenko
