### ISSUE TITLE
Consider using the x-systemd.growfs option in /etc/fstab

### ISSUE THREAD

**Issue by stapelberg** [Debian/raspi3-image-spec#43]
Just found this by chance and thought it might help here — maybe we can drop rpi3-resizerootfs entirely :).

See https://manpages.debian.org/testing/systemd/systemd.mount.5.en.html#FSTAB and https://manpages.debian.org/testing/systemd/systemd-makefs@.service.8.en.html for more details.

cc @chschlue @gwolf

**Comment by gwolf** [comment]
seems trivial to address, but I haven't looked yet into this :-P Anyway, moving to Salsa as [issue number 2](https://salsa.debian.org/raspi-team/image-specs/issues/2)
