### ISSUE TITLE
QT says Could not initialize GLX

### ISSUE THREAD

**Issue by yazdan** [Debian/raspi3-image-spec#51]
Hi,

I've install Debian image on my RPI3 to use QT webengine. My custom application don't start and I also tested Qutebrowser. This one is also not working. Both of them have following error
`Could not initialize GLX`

I thinks this is related to GLX and EGLFS of QT5 on RPI. I've added `dtoverlay=vc4-fkms-v4d` to `\boot\config.txt` to make sure that OpenGL is enabled. I also have installed  `mesa-utils` and can run `glxgears` successfully.

I don't know any tool to investigate such bugs, so please help me to investigate this issue more effectively.

Thanks,
Abbas

**Comment by gwolf** [comment]
I am moving this issue over to salsa.debian.org [issue number 3](https://salsa.debian.org/raspi-team/image-specs/issues/3).
