### ISSUE TITLE
enable SND_SIMPLE_CARD

### ISSUE THREAD

**Issue by norbusan** [Debian/raspi3-image-spec#57]
Hi Gunnar

I recently got onto the rpi3 wagon for a home made smart speaker ... sooo

To support the respeaker hat https://github.com/respeaker/seeed-voicecard.git we would need CONFIG_SND_SIMPLE_CARD be available. Is there a reason why this is disabled and could it be enabled?

Furthermore, any plan to support the device tree overlay stuff raspian is doing, again to get support for the respeaker ;-)

**Comment by gwolf** [comment]
Hi,

I am migrating the project over to salsa.debian.org. I am copying this issue as [salsa.debian.org issue #6](https://salsa.debian.org/raspi-team/image-specs/issues/6).
