### ISSUE TITLE
Boot partition contains three different kernel images

### ISSUE THREAD

**Issue by pavellaminar** [Debian/raspi3-image-spec#61]
Image 20190628_raspberry-pi-3_buster_PREVIEW.img.xz in first partition contains hree different kernel images kernel.img, kernel7.img, vmlinuz-4.19.0-5-arm64

![2019-07-09_10-04-34](https://user-images.githubusercontent.com/16295983/60945092-1213e080-a304-11e9-926f-37ce303ce1e3.png)

**Comment by licaon-kter** [comment]
@pavellaminar please rephrase this

**Comment by SuperSandro2000** [comment]
The first parition (boot) partition of ``Image 20190628_raspberry-pi-3_buster_PREVIEW.img.xz`` contains three different kernel images, namely ``kernel.img``, ``kernel7.img`` and ``vmlinuz-4.19.0-5-arm64``.

**Comment by licaon-kter** [comment]
yes, and `config.txt` instructs it to load the correct one, `vmlinuz-4.19.0-5-arm64` and `initrd`, right?

**Comment by gwolf** [comment]
Hi,

I am moving the project over to salsa.debian.org, and copied this issue as [salsa.debian.org issue #8](https://salsa.debian.org/raspi-team/image-specs/issues/8). Please refer to it for further information.

**Comment by gwolf** [comment]
Hi,

I am moving the project over to salsa.debian.org, and copied this issue as [salsa.debian.org issue #8](https://salsa.debian.org/raspi-team/image-specs/issues/8). Please refer to it for further information.
